# Monitor Application
spring.application.name=monitor

# Use a different port from the backend
server.port=8081

# Enable JMX
spring.jmx.enabled=true

# Expose all actuator endpoints
management.endpoints.web.exposure.include=*

# Enable JVM metrics
management.endpoint.metrics.enabled=true
management.endpoint.health.enabled=true
management.endpoint.info.enabled=true

# Enable shutdown endpoint (optional)
management.endpoint.shutdown.enabled=true

# Show startup logs
logging.level.root=INFO